title: Andrea Troise
logo: /Pics/IMG_1114.jpg
description: Hi! My name is Andrea Troise, you ended up in this small corner of the internet which is my personal resume. It is also the place that I am going to use to dump some of the amazing stuff that I get to do in my life!
show_downloads: false
theme: jekyll-theme-minimal
