title: Andrea Troise
logo: /Pics/IMG_2667.JPG
description: Hi! My name is Andrea Troise, you ended up in this small corner of the internet which is my personal webpage! Here you can find something about me...
show_downloads: false
theme: jekyll-theme-minimal
